### ISSUE TITLE
Error in Ubuntu 18.10 on Samsung Galaxy Book 10.6

### ISSUE THREAD

**Issue by githubtest990** [devrikx/atheros#2]
Hello,

I keep encountering a problem in Ubuntu 18.10,
when trying to make the file, as below:

~/atheros$ make -C /lib/modules/$(uname -r)/build M=$(pwd) modules
make: Entering directory '/usr/src/linux-headers-4.18.0-11-generic'
  CC [M]  /atheros/ath9k/main.o
/atheros/ath9k/main.c: In function ‘ath9k_fill_chanctx_ops’:
/atheros/ath9k/main.c:2635:37: error: assignment to ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, u16)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, short unsigned int)’} from incompatible pointer type ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *)’ [-Werror=incompatible-pointer-types]
  ath9k_ops.mgd_prepare_tx           = ath9k_mgd_prepare_tx;
                                     ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:327: /atheros/ath9k/main.o] Error 1
make[1]: *** [scripts/Makefile.build:581: /atheros/ath9k] Error 2
make: *** [Makefile:1546: _module_/atheros] Error 2
make: Leaving directory '/usr/src/linux-headers-4.18.0-11-generic'

Now this is on the Samsung Galaxy Book 10.6, not the 12. But I assume it will appear on both devices.

**Comment by githubtest990** [comment]
my account was flagged for some reason so not sure if this will be visible

**Comment by kirvedx** [comment]
Hmm, It's visible but I didn't see it in my email - sorry for the delay:

You are using the **master** branch for this right?  Seems you're using the 4.18 kernel, but you seem to be on a kernel version that is at a ridiculously higher package-version than the one we have on Debian testing/Sid right now `4.18.0-3-amd64`.

I can confirm on my 12, and using Debian Sid (or maybe it is just *testing*, and not *experimental*), that I have just recompiled for the 4.18.0-3 kernel update that I installed yesterday using the master branch.  I had no errors, and its working flawlessly (writing this response on it right now).

**Comment by kirvedx** [comment]
I'm going to close this issue as there is now support for kernel versions up-to-and-including 5.5 #5, #6).

If you leverage the later sources provided in this repository and find yourself still having problems feel free to reopen this - or submit a new - issue!
